### ISSUE TITLE
python package

### ISSUE THREAD

**Issue by gabor1** [BingqingCheng/ASAP#11]
hi guys!

What is the plan and timescale of making this an installable python package? We are trying to use ASAP in a toolchain together with other tools, and finding it more difficult to work with it as is, paths need to be set specially etc. All this would go away if ASAP was installable as a python package.

**Comment by BingqingCheng** [comment]
We'll need to discuss a bit about this. Do you mean that you want to import ASAP as a library? IMO, given the current design, it makes more sense to add a script to install it (aka. adding the location of the package to PYTHONPATH).

**Comment by gabor1** [comment]
No not as a library. I understand that these are scripts. I would like these scripts to be installed in "standard" places, so that they can be found on the standard PATH that conda or other python installations use. (PYTHONPATH is for modules only). 

-- Gábor

**Comment by BingqingCheng** [comment]
Okay. I see. I'll dig up on how to do this.

**Comment by gabor1** [comment]
a good test is whether the system() method from python can execute them...

-- Gábor

**Comment by Ryan-Rhys** [comment]
I've created a mock python package for ASAP on TestPyPI:

https://test.pypi.org/project/ASAP/

scripts are executable via the `os.system()` method. If this feature is satisfactory I can make a 'proper' python package that will install third-party dependencies like numpy!

**Comment by BingqingCheng** [comment]
Fantastic. I tried it, seems to be working great!

**Comment by gabor1** [comment]
I can install the package, but I can’t then find the commands: 

docker:~$ pip install -i https://test.pypi.org/simple/ ASAP
Looking in indexes: https://test.pypi.org/simple/
Collecting ASAP
  Downloading https://test-files.pythonhosted.org/packages/ff/5b/9c214122c76f847d8643f9b85c578fbd3a6d8258c68e9c90038b467931f3/ASAP-0.0.1-py3-none-any.whl (55 kB)
     |████████████████████████████████| 55 kB 3.2 MB/s 
Installing collected packages: ASAP
Successfully installed ASAP-0.0.1
docker:~$ gen_soap_descriptors.py 
bash: gen_soap_descriptors.py: command not found
docker:~$ echo $PATH
/opt/lammps/src/:/opt/quip/src/AtomEye/bin:/opt/quip/bin:/opt/julia/v1.1.0/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
docker:~$ 


-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory, University of Cambridge
Pembroke College Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/

**Comment by Ryan-Rhys** [comment]
Are the commands findable with this package?

https://test.pypi.org/project/ASAP2/0.0.3/

**Comment by gabor1** [comment]
yes - they are now in /usr/local/bin. Do they always end up there, or do you have a way of figuring out where the current python environment likes to keep executables? 

-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory, University of Cambridge
Pembroke College Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/

**Comment by Ryan-Rhys** [comment]
Yep, this is a problem because the scripts will be run by the system python. I'll look into how to ensure that they're run by the venv python!

**Comment by Ryan-Rhys** [comment]
Apologies for the delay in responding; I have two conference submission deadlines over the coming two weeks and so these are demanding most of my attention! 

With a command such as:

`pip install -i https://test.pypi.org/simple/ ASAP2==0.0.3 --install-option="--install-scripts=path/to/custom_script_location"`

it should be possible to specify a custom path to house the scripts. I can create a temporary python package on TestPyPi (@BingqingCheng presumably we're not ready to release on PyPi) now if this would substantially speed up your workflow?

**Comment by Wangmumu0403** [comment]
I have trouble in asap-select 
`sap select  -n 100 -f dataset.xyz`
it shows: 
`ataset.xyz  
load xyz file:  dataset.xyz , a total of  3052 frames , a total of  439488 atoms , with elements:  [3, 5, 8] .
Find the following descriptor names that match the specifications:  ['']
Traceback (most recent call last):
  File "/home/hp/.local/lib/python3.8/site-packages/asaplib-0.0.1-py3.8.egg/asaplib/data/xyz.py", line 448, in get_descriptors
  File "<__array_function__ internals>", line 5, in hstack
  File "/usr/lib/python3/dist-packages/numpy/core/shape_base.py", line 337, in hstack
    arrs = atleast_1d(*tup)
  File "/home/hp/.local/lib/python3.8/site-packages/asaplib-0.0.1-py3.8.egg/asaplib/data/xyz.py", line 449, in <genexpr>
  File "/home/hp/.local/lib/python3.8/site-packages/asaplib-0.0.1-py3.8.egg/asaplib/data/xyz.py", line 449, in <listcomp>
KeyError: ''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hp/.local/bin/asap", line 11, in <module>
    load_entry_point('asaplib==0.0.1', 'console_scripts', 'asap')()
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/hp/.local/lib/python3.8/site-packages/asaplib-0.0.1-py3.8.egg/asaplib/cli/cmd_asap.py", line 72, in select
  File "/home/hp/.local/lib/python3.8/site-packages/asaplib-0.0.1-py3.8.egg/asaplib/cli/func_asap.py", line 80, in read_xyz_n_dm
  File "/home/hp/.local/lib/python3.8/site-packages/asaplib-0.0.1-py3.8.egg/asaplib/data/xyz.py", line 452, in get_descriptors
IndexError: list index out of range
`

**Comment by Wangmumu0403** [comment]
I have trouble in asap select 

```
asap select  -n 100 -f dataset.xyz
```
then shows error
```
load xyz file:  dataset.xyz , a total of  3052 frames , a total of  439488 atoms , with elements:  [3, 5, 8] .
Find the following descriptor names that match the specifications:  ['']
Traceback (most recent call last):
  File "/home/hp/.local/lib/python3.8/site-packages/asaplib-0.0.1-py3.8.egg/asaplib/data/xyz.py", line 448, in get_descriptors
  File "<__array_function__ internals>", line 5, in hstack
  File "/usr/lib/python3/dist-packages/numpy/core/shape_base.py", line 337, in hstack
    arrs = atleast_1d(*tup)
  File "/home/hp/.local/lib/python3.8/site-packages/asaplib-0.0.1-py3.8.egg/asaplib/data/xyz.py", line 449, in <genexpr>
  File "/home/hp/.local/lib/python3.8/site-packages/asaplib-0.0.1-py3.8.egg/asaplib/data/xyz.py", line 449, in <listcomp>
KeyError: ''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hp/.local/bin/asap", line 11, in <module>
    load_entry_point('asaplib==0.0.1', 'console_scripts', 'asap')()
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/hp/.local/lib/python3.8/site-packages/asaplib-0.0.1-py3.8.egg/asaplib/cli/cmd_asap.py", line 72, in select
  File "/home/hp/.local/lib/python3.8/site-packages/asaplib-0.0.1-py3.8.egg/asaplib/cli/func_asap.py", line 80, in read_xyz_n_dm
  File "/home/hp/.local/lib/python3.8/site-packages/asaplib-0.0.1-py3.8.egg/asaplib/data/xyz.py", line 452, in get_descriptors
IndexError: list index out of range
```

**Comment by BingqingCheng** [comment]
It looks to me that the dataset.xyz doesn’t contain descriptors, which are
needed for the sparsification. Please try to use asap gen_desc to generate
the descriptors first.
