### ISSUE TITLE
compute_atomic_descriptors fails when sbs isn't passed in

### ISSUE THREAD

**Issue by bernstei** [BingqingCheng/ASAP#57]
in data/xyz.c `compute_atomic_descriptors()` fails on line 209 when `sbs` is passed in as `[]`, because it does `self.frames[sbs]` but this is not valid when `sbs` is the result of `range()`, as is the case when you pass in `[]` (line 199).  The full traceback is 
```
Traceback (most recent call last):
  File "asap_manual.py", line 36, in <module>
    asapxyz.compute_atomic_descriptors(desc_spec_dict=soap_spec, sbs=[])
  File "/home/cluster2/bernstei/.local/lib/python3.6/site-packages/asaplib-0.0.1-py3.6.egg/asaplib/data/xyz.py", line 209, in compute_atomic_descriptors
TypeError: list indices must be integers or slices, not range
```
If you want a reproducing script, let me know. It's already in a loop over `sbs`, so line 209 probably just needs to be `[i]` instead of `[sbs]`.

**Comment by bernstei** [comment]
Fixing that leads to an error in the next line, 210:
```
Traceback (most recent call last):
  File "./asap_manual.py", line 38, in <module>
    asapxyz.compute_atomic_descriptors(desc_spec_dict=soap_spec, sbs=[], n_process=4)
  File "/home/cluster2/bernstei/.local/lib/python3.6/site-packages/asaplib-0.0.1-py3.6.egg/asaplib/data/xyz.py", line 210, in compute_atomic_descriptors
AttributeError: 'Atomic_Descriptors' object has no attribute 'create'
```

**Comment by BingqingCheng** [comment]
fixed now
